DEFAULT_PORT = 7878

REQUEST_CREATE_ROOM = '4'
REQUEST_ROOMS = '5'
RESPONSE_OK = "1"
PRINT_MESSAGE = "2"
CLIENT_START_LISTEN = "3"
START_GAME = "4"
PEOPLE_CHANGED = "5"
SUDOKU_CHANGED = "6"
GET_SCORE = "7"
SET_NAME = "8"
GET_ROOMS = "9"