DEFAULT_PORT = 7878
DEFAULT_SERVER_INET_ADDR = "127.0.0.1"

REQUEST_CREATE_ROOM = '4'
RESPONSE_OK = "1"
RESPONSE_ERROR ='0'

TOO_LATE = "-1"
FULL_ROOM = '-2'
ROOM_NOT_FOUND = '-3'
NOT_FOUND = "404"
CLIENT_START_LISTEN = "3"
START_GAME = "123"
PEOPLE_CHANGED = "5"
SUDOKU_CHANGED = "6"
SET_SUDOKU_VALUE = "11"
SET_NAME = "8"
GET_ROOMS = "9"
JOIN_ROOM = "10"
SUDOKU_SOLVED = "342"
LEAVE_ROOM = "432"