SUBMIT_NICKNAME = 'SUBMIT_NICKNAME'
MESSAGE = "MESSAGE"
CONNECT_TO_SERVER = 'CONNECT_TO_SERVER'
ERROR_CONNECTING_TO_SERVER = 'ERROR_CONNECTING_TO_SERVER'
CONNECTED_TO_SERVER = 'CONNECTED_TO_SERVER'
LOAD_ROOMS = 'LOAD_ROOMS'
ROOMS_LOADED = 'ROOMS_LOADED'

ERROR_OCCURRED = 'ERROR_OCCURRED'