SUBMIT_NICKNAME = 'SUBMIT_NICKNAME'
MESSAGE = "MESSAGE"
CONNECT_TO_SERVER = 'CONNECT_TO_SERVER'
HOST = 'HOST'
CONNECTED_TO_SERVER = 'CONNECTED_TO_SERVER'
CREATE_ROOM = 'CREATE_ROOM'
ROOM_CREATED = 'ROOM_CREATED'
LOAD_ROOMS = 'LOAD_ROOMS'
ROOMS_LOADED = 'ROOMS_LOADED'
CELL_EDITED = 'CELL_EDITED'
ROOM_JOINED = "ROOM_JOINED"
GAME_ENDED = 'GAME_ENDED'
LEAVE_ROOM = "LEAVE_ROOM"
ROOM_LEAVED = "ROOM_LEAVED"

ERROR_CONNECTING_TO_SERVER = 'ERROR_CONNECTING_TO_SERVER'
ERROR_TOO_LATE = 'ERROR_TOO_LATE'
ERROR_FULL_ROOM = 'ERROR_FULL_ROOM'
ERROR_ROOM_NOT_FOUND = 'ERROR_ROOM_NOT_FOUND'
ERROR_OCCURRED = 'ERROR_OCCURRED'

JOIN_GAME = 'JOIN_GAME'
