SUBMIT_NICKNAME = 'SUBMIT_NICKNAME'
MESSAGE = "MESSAGE"
CONNECT_TO_SERVER = 'CONNECT_TO_SERVER'
ERROR_CONNECTING_TO_SERVER = 'ERROR_CONNECTING_TO_SERVER'
CONNECTED_TO_SERVER = 'CONNECTED_TO_SERVER'
CREATE_ROOM = 'CREATE_ROOM'
ROOM_CREATED = 'ROOM_CREATED'
LOAD_ROOMS = 'LOAD_ROOMS'
ROOMS_LOADED = 'ROOMS_LOADED'

ERROR_OCCURRED = 'ERROR_OCCURRED'

JOIN_GAME = 'JOIN_GAME'

QUIT = 'QUIT'